### PR TITLE
Handling data download from CDS era5 database

### PR DESCRIPTION
**Pull request by Bachibouzouk**
The data is requested from https://cds.climate.copernicus.eu/cdsapp#!/home, using the python package `cdsapi`

### CODE REVIEW

**Comment by Bachibouzouk** [comment]
@birgits - I noticed that the requested is queued for a long time, unless the same request is first made through their online app. Then any new request with the same parameters made from the local station is completed very quickly. I have sent an inquiry to their customer support about that issue.

**Comment by Bachibouzouk** [comment]
I still have to work out the preparation of the position as a function of the grid size. However, I wrote down the functions definitions, let me know if it is what you had in mind :)

@birgits - let me know if you have found which variables are relevant among those I sent you
@Piranias - let me know what other variable(s) you would like to extract from the database and

**Comment by Bachibouzouk** [comment]
@birgits - it starts to have many commits, it should maybe be merged. Future improvments can be performed subsequently

**Comment by Bachibouzouk** [comment]
@birgits - you were already on the merging job as I commented ;) 
You can also delete the branch, to avoid having too many merged branches lying around

**Comment by birgits** [comment]
Thanks again for your help yesterday @Bachibouzouk :)

**Pull request merged**
