### PR TITLE
Add geometric solar model

### PR DESCRIPTION
**Pull request by p-snft**
We, Lucas, Keno and me, suggest to add a simple geometric solar model (PV or ST) to allow for fast calculations without using pvlib.

To do:
- [x] (More) documentation
- [x] Unit tests

To reduce the amount of code in the single files to an acceptable level, the PR also splits the models module into submodules.

### CODE REVIEW

**Comment by uvchik** [comment]
Cool. I like the idea.

What do you think about the integration of existing tools for the calculation of the position of the sun?

**Comment by p-snft** [comment]
> What do you think about the integration of existing tools for the calculation of the position of the sun?

The actual calculation of the position of the sun just depends on a very limited number of calculations that we transferred straight from a textbook ([DOI:10.1002/9781118671603](https://onlinelibrary.wiley.com/doi/book/10.1002/9781118671603), needs to be added to the documentation). We wanted to have it simple, so it is reasonable to be implemented without external dependencies.

**Comment by uvchik** [comment]
Sound reasonable and Duffi/Beckman is definitely a good source :smile:

**Comment by p-snft** [comment]
@oemof/feedinlib: Would you give feedback, please?

**Comment by p-snft** [comment]
If there is no objection until end of January, I will merge this.

**Pull request merged**
